name: Test
on:
  push:
    # branches:
    #   - "main"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2019]
    steps:
      - uses: actions/checkout@v3
      - run: |
          julia
  validate_tests:
    runs-on: ["ubuntu-latest"]
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v2
      - run: |
          julia --project=. -e 'using Pkg; Pkg.instatiate(); Pkg.precompile(); Pkg.test()'
